### ISSUE TITLE
Firefox: requests from DevTools not authenticating

### ISSUE THREAD

**Issue by klaus-aunds** [krtek4/MultiPass#105]
First: thanks a lot for maintaining this extension, it has saved me many hours of typing credentials!

The issue:
Loading source maps from Firefox' DevTools generates a new request to the website. The basic auth authentication only works if the credentials are already saved in Firefox' password manager. Otherwise it'll just fail with a 401. MultiPass doesn't manage this requests at the moment.

Steps to reproduce:
- website with source maps available, behind basic auth
- configure MultiPass for the website
- make sure that basic auth for the website is not saved in Firefox password manager
- load website, MultiPass takes care of the authentication
- open DevTools
- open Debugger tab in DevTools
- select a script with available source map
- 401 error displayed

<img width="1205" alt="Bildschirmfoto 2024-08-16 um 15 23 06" src="https://github.com/user-attachments/assets/07e2eb38-5fc7-438e-a539-7b980d738f03">

Possible solutions:
The most logical solution would be to let MultiPass handle these requests too, but I'm unsure if that's possible. Saving the credentials successfully managed by MultiPass into the Firefox password manager automatically could be an option, but implementing it may not be possible and it's a feature some users would prefer not to have.

**Comment by krtek4** [comment]
Hello,

Thanks for the kind words.

Regarding your issues, I am afraid that the extension already has all the possible rights to handle all kinds of requests and if it doesn't work for sourcemaps I am fairly certain there's nothing I can do. In my opinion, it's more of a bug of Firefox and you could maybe open a ticket here on firefox ( https://bugzilla.mozilla.org/home ) to let them know.

As for saving the credentials in the password manager, again I am not certain, but I am fairly sure that extension are sandboxed from it in order to avoid any security issue.

Also, sadly, I don't use the extension anymore and don't have time to work on it. If it had been an easy fix I would have made it, but this would surely involve a lot of research just to determine if it's feasible. I will gladly merge any kind of pull request improving the extension or offer a bit of help, but I can't start working on something like that.

Sorry not being more helpful, cheers.
