### ISSUE TITLE
(Chrome) Auto login not working when doing hard refresh

### ISSUE THREAD

**Issue by Swanty** [krtek4/MultiPass#41]
Great extension, but if you do Ctrl+Shift+R then chrome will show the basic auth popup and as a developer I quite often have to use hard refresh =(

**Comment by krtek4** [comment]
Hi,

I am unable to reproduce the issue on my side. Can you give me a little more details?

Is it possible for you to give me an URL where the issue arise? Otherwise maybe the web server configuration that is performing the authentication?

Cheers,

**Comment by Swanty** [comment]
Unfortunately I cannot give an example URL, since it's a private company domain, but I can sure give some more details.

We have a website where anything under sub.domain.tld requires basic auth, even static content like sub.domain.tld/favicon.ico

- If I open the sub.domain.tld MultiPass works great
- If I press Ctrl + R then MultiPass works great
- If I press Ctrl + Shift + R or Ctrl + F5 chrome asks me to authenticate what seems to be like forever
Every time I do hard refresh, chrome shows the auth popup and when I input credentials and press Log-In, chrome just shows the same popup again, asking for credentials and it goes on and on and on and on....
You can also just simply open Dev tools in Chrome (F12) and go to Network tab and check the box that says "Disable cache" and it becomes impossible to open a basic auth page.

Perhaps you have a basic auth page that I can test on? Maybe it's really the nginx config that's wrong, though it works ok for normal refresh.

**Comment by Swanty** [comment]
nginx config has this inside the server block:

~~~
        satisfy any;
        allow 10.10.20.0/26;
        allow 10.10.10.44;
        deny  all;
        auth_basic           "closed site";
        auth_basic_user_file .nginxpasswd;
~~~

**Comment by krtek4** [comment]
I found this website to test basic auth: https://httpbin.org/basic-auth/user/passwd. The username is "user" and the pw is "passwd". You can change those by changing the values in the URL. I just tested a bit and wasn't able to reproduce the issue.

Like you are describing it, it seems to me the issue is on the server side. Do you have some kind of load balancing or something?

I think the fact that even if you enter the credentials manually does not work clearly indicate that the culprit is not the extension. The way it works, it should not matter if it's a first load, reload or hard reload.

**Comment by Swanty** [comment]
You are right, the link you provided works for me even with hard reload.

Will try to fix the nginx config and report back.

**Comment by Swanty** [comment]
Varnish with wrong auth config in front of nginx was the problem lol

Thank you very much for help!
