### ISSUE TITLE
Issue with multiple regex on same domain

### ISSUE THREAD

**Issue by jallakim** [krtek4/MultiPass#51]
Hi,

There seems to be some issues when having multiple regex-entries for the same top-domain.

The following seems to work;

| Domain | Username | Password | 
| -------- | ---------- | --------- |
| .\*\\.foo\\.bar | user1 | user1 |
| .\*lol.\*\\.foo\\.bar | user2 | user2 |
| .\*kek.\*\\foo\\.bar | user2 | user2 |

However, trying to merge the two latter into one entry;

| Domain | Username | Password | 
| -------- | ---------- | --------- |
| .\*\\.foo\\.bar | user1 | user1 |
| .\*(lol\|kek).\*\\.foo\\.bar | user2 | user2 |

This does not seem to work (it seems to be using `user1/user1` when logging into domains containing `lol` and `kek`).

Using the regex-matching-test-thingie seems to give expected result.

**Comment by krtek4** [comment]
Hi,

Thanks for reporting the issue.

Off the top of my head I would say there is absolutely no sorting of the rules, so the engine check them in whatever order they are stored in the array. I imagine the order is different in your two examples due to some internal storage design of the javascript engine.

Can you confirm the little icon is yellow when accessing the website to indicate there is multiple matches for the domain in both cases ?

I am not sure what is the obvious solution. We could sort the rules by length of the regexps, but the longest won't necessarily be the more specific. Another option would be to take the order in the GUI into account and let the user drag & drop the rules to change their position.

Since you are encountering the issue, what would be your preferred solution ?

**Comment by jallakim** [comment]
I guess the most simple way to solve this, would be to introduce a new field (`Priority` or similar), where you can put a user-defined number. When you have multiple results for a given site, use the one with the lowest (or highest) number first. This would make it easy to change the order on-the-fly, and you don't need to introduce "ordering" (i.e. actual sorting of things).

**Comment by krtek4** [comment]
I added a priority field, can you test the latest release before I publish it on the store : https://github.com/krtek4/MultiPass/releases/tag/v0.7.3

**Comment by jallakim** [comment]
Hi,

Thanks. Seems to be working so far. I guess the order they are sorted in the list is the order they are treated? (i.e. the higher the number, the lower preference it has).

**Comment by krtek4** [comment]
Yes, higher the number, lower the preference... I didn't know what was the best option ^^

I'll release later this afternoon.

**Comment by krtek4** [comment]
Just released on the three addon stores, update should be automatically applied shortly. I am closing this on the meantime :)

**Comment by jallakim** [comment]
@krtek4, thanks, it's already "live".

One thing; maybe the "priority"-column should get a name? Currently it's just blank, and the field without context might not be self-explanatory.

**Comment by krtek4** [comment]
You're right, the translation message was missing, I was a bit hasty releasing.

I just pushed version 0.7.4 which should fix that.

**Comment by jallakim** [comment]
@krtek4, great! Thanks!
