### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by RowanKaag** [krtek4/MultiPass#53]
Hey!

Thank you for writing this extension for Firefox and Chrome! Such a small extension that greatly simplifies an annoying basic auth pop-up. Gladly using this to automatically log me in into Transmission for example, which does basic auth by default (and afaik, is not configurable).

Now, my main browser is Safari and I practically only use any other browser if I really have to. Would it be possible to port this plug-in to a Safari extension? I'd be happy to help anywhere I can.

**Comment by krtek4** [comment]
Hey @RowanKaag,

I quickly searched the internet about Safari WebExtensions and from what I gathered I need to register for the "Apple Developer Program".

I would gladly do it, except it costs around 100$ per year.

Since I don't plan on developing anything else for the Apple platform, this seems a bit pricey.

If you are yourself a certified Apple developer or if you can find some kind of "sponsor" to upload the extension, I would gladly give a hand, but as it is, it seems complicated for me alone.

Best,

**Comment by RowanKaag** [comment]
Dear @krtek4 

I can image that not having the Developer account (which I also do not own, unfortunately) - and only having this extension published (for free?) doesn't cut the deal. Unfortunate, but understandable!
