### ISSUE TITLE
Basic Auth across different urls belonging to the same domain doesn't work

### ISSUE THREAD

**Issue by takearun** [krtek4/MultiPass#57]
Hi,
I use the chrome extension.
My urls are like this,

> https://somedomain.com/logs
> https://somedomain.com/documents

both protected by different basic auth. 
Extension passes the same basic auth to both URLs.

I haven't used any regexes, i just set the whole url as is. I did verify it with the tester.

It might be because Chrome stores the credentials against the domain - but that's exactly what I want to avoid using this extension.

Any help is appreciated.

Thanks,
Arun

**Comment by krtek4** [comment]
Hi Arun,

Thanks for the bug report.

The extension should check against the whole URL, so in theory your setup should work.

I however had some issues myself with newer version of Chrome, I need to make some more tests and get back to you.

Best,

**Comment by takearun** [comment]
Hi Gilles,
Thank you so much for a quick response. Waiting for hear back.

Thanks,
Arun

**Comment by krtek4** [comment]
Hi @takearun,

I did some tests and it works fine when copy-pasting the whole URL in the extension *except* if the URLs contain some symbols like `?` which are interpreted by the regex engine.

If you want some more help, you will need to provide the real URLs you are using so that I can pinpoint if there is some other issues at hand. Feel free to drop me an e-mail if you don't want those being public here :)

Best,

**Comment by krtek4** [comment]
You can find it on my personal website: https://gilles.crettenand.info/
