### ISSUE TITLE
The extension doesn't work in incognito mode

### ISSUE THREAD

**Issue by Velikodn** [krtek4/MultiPass#62]
Hi. After a week of using this extension, the extension has stopped working in incognito mode. 

Win 10. Google Chrome 72.0.3626.96 (Official Build) (64-bit)

**Comment by krtek4** [comment]
Hi,

I just tried with the same version as you and it worked fine.

What do you mean by "stopped working" ? Do you have an error ? Did the credentials stopped being sent ?

Is the extension allowed in incognito in the config: chrome://extensions/?id=ledpdddbhgkjamhagllpgabamgaadbff ? (if my link doesn't work, go to chrome://extensions/ and click "Details" on Mutlipass)

**Comment by Velikodn** [comment]
Hi [krtek4](/krtek4). 
I mean, that the extension I have worked in a normal browser mode and incognito mode. And the day before yesterday, this extension stopped working only in incognito mode. Data for HTTP not automatically filled in incognito mode but there're no any errors.

**Comment by krtek4** [comment]
As far as I know, there are no differences between normal and incognito that could explain this.

Is the extension allowed in incognito ? Is the extension icon displayed in the top bar in incognito ?

Could you have any extension that modify the behavior of the browser in incognito mode ?

I tested again with multiple websites and a blank profile, the extension works fine in incognito for me on the same Chrome version.

Do you have friends and colleagues that can reproduce the faulty behavior ? Can you maybe try on another computer if the error persists ?

**Comment by Velikodn** [comment]
1. Yes. The extension allowed in incognito and the extension icon displayed in the top bar in incognito

2. I don't have any extension that modifies the behavior of the browser in incognito mode

3. In three of my five friends, this error is relevant

We reinstalled this extension and it didn't help.

**Comment by krtek4** [comment]
Hi @Velikodn,

I tried again, but impossible for me to reproduce any kind of issue in incognito mode.

In order to help you debug this issue further could you provide me with the following:

* Operating System you and your friends are runing
* The list of websites for which the extension does not work
* A screenshot of the dropdown menu opened in "normal" mode when a credential was sent (with the address bar visible), you should see a little green square on the bottom left of the icon
* A screenshot of the dropdown menu opened in "incognito" mode

I'd also ask for the credentials, but I imagine this is not possible :)

I hope we can resolve this together.

Best,

**Comment by krtek4** [comment]
Closing this as there was no further activity :)
