### ISSUE TITLE
crx2 deprecated , extension verification failed in latest google chrome beta

### ISSUE THREAD

**Issue by muhammadumair66** [krtek4/MultiPass#66]
Please fix it ! Thanx

**Comment by krtek4** [comment]
Hi @muhammadumair66,

Thanks for reporting this, I'll try to update a new version of the package next week.

**Comment by raul4916** [comment]
It seems that it is failing on the Stable chrome build 
Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by krtek4** [comment]
I wanted to update the package the other day, sadly I have issues with my development environement and absolutely no time right now to figure out how to migrate gulp to the new version.

I'll try to find some time this weekend to see if I can get the build script working, but I'm not really confident.

Sorry

**Comment by raul4916** [comment]
No rush, was just giving heads up 👍

**Comment by krtek4** [comment]
@muhammadumair66 @raul4916 

Just submitted a new 0.9.0 version to the Chrome webstore. Hope it fixes the issue.

The new version is pending review due to little changes in their conditions, but I am confident it should be present in the store in the next few days.

Closing this in the meantime, let me know if the new package still does not work for you.

Best,
