### ISSUE TITLE
Extension not passing Credentials by using local html page

### ISSUE THREAD

**Issue by amjadalbarail** [krtek4/MultiPass#69]
Hello there , 
i have created html page , which present multiple pages using iframe. the extension doesnt pass now the http basic authenication anymore after chrome update.
but if i go directly to any link of those , the credintials works perfectly. 
Is there any solution? 
thanks

**Comment by krtek4** [comment]
Hi There,

Sadly no, there's nothing that I can do, I am 100% dependent on the browser to ask for the credentials.

The browser mechanism isn't triggered in case of iframes or any kind of embedded content (see https://github.com/krtek4/MultiPass/issues/65 for the same issues with images for exemple). The reason is security.

Best,
