### ISSUE TITLE
key in the crx header not matched with the key in manifest

### ISSUE THREAD

**Issue by wessam1292** [krtek4/MultiPass#70]
key in the crx header not matched with the key in manifest

**Comment by krtek4** [comment]
Hi @wessam1292,

Not sure what you mean by that ?

There are no keys in the manifest and the while signing process is done by the various stores where the extension is uploaded.

Can you give me more details about what the issue is for you ?

Best,

**Comment by wessam1292** [comment]
i am trying to simulate google chrome in selenium and i am trying to avoid authentication popup , when i upload crx in selenium and start it is giving me an error that "key in crx header is different from key in manifest file" also the extension ID is different

**Comment by krtek4** [comment]
As I said, the CRX signing is done by the Chrome Extension Store. So you should check with them what the issue is.

You can check for yourself that the manifest in the repository does not have any key ( https://github.com/krtek4/MultiPass/tree/master/vendor/common and https://github.com/krtek4/MultiPass/tree/master/vendor/chrome ). Those are added when the extension is uploaded on the various stores (see https://developer.chrome.com/apps/manifest/key ).

You could eventually add a key yourself and re-package the extension if need be.
